<div class="row">
	<div class="col-md-12">&nbsp;</div>
</div>
<div class="col-md-8 col-md-offset-2" >
	<form id="form" role="form" action="<?= BASE_URL;?>permisos/actionAgregar/" method="POST">
		<legend>Agregar Permisos</legend>
		<div class="row" >
		2<div class="form-group control-group col-md-2">
			<label for="id_per" class="control-label">id_per</label>
			<div class="controls">
				<input type="number" class="form-control" name="Permisos[id_per]" id="id_per" placeholder="id_per">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="fk_per" class="control-label">fk_per</label>
			<div class="controls">
				<input type="text" class="form-control" name="Permisos[fk_per]" id="fk_per" placeholder="fk_per">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="nom_per" class="control-label">nom_per</label>
			<div class="controls">
				<input type="text" class="form-control" name="Permisos[nom_per]" id="nom_per" placeholder="nom_per">
			</div>
		</div>
</form>
</div>
