<div class="row">
									<div class="col-md-12">&nbsp;</div>
								</div>
<div class="col-md-8 col-md-offset-2" >
							?????3<form id="form" role="form" action="<?= BASE_URL;?>permisos/actionAgregar/" method="POST">
										<legend>Agregar Permisos</legend>
<div class="row" >
																										<div class="form-group control-group col-md-2">
															<label for="id_per" class="control-label">id_per</label>
																	<div class="controls">
																		<input type="number" class="form-control" name="Permisos[id_per]" id="id_per" placeholder="Grado" autofocus>
															</div>
												</div>
</form>
</div>
