<div class="row">
	<div class="col-md-12">&nbsp;</div>
</div>
<div class="row" >
	<div class="col-md-8 col-md-offset-2" >
		<form id="form" role="form" action="<?= BASE_URL;?>/action/" method="POST">
			<legend>Consultar Permisos</legend>
			<div class="form-group control-group col-md-2">
				<label for="fk_per" class="control-label">fk_per</label>
				<div class="controls">
					<input type="text" class="form-control" name="permisos[fk_per]" id="fk_per" placeholder="fk_per">
				</div>
			</div>
			<div class="form-group control-group col-md-2">
				<label for="nom_per" class="control-label">nom_per</label>
				<div class="controls">
					<input type="text" class="form-control" name="permisos[nom_per]" id="nom_per" placeholder="nom_per">
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 col-md-offset-0" >
					<a href="			<?= BASE_URL;?>permisos/actionConsultar/" class="btn btn-primary col-md-offset-1"  role="button">Volver</a>
				</div>
			</div>
		</form>
	</div>
		</div>
	