<div class="row">
					<div class="col-md-12">&nbsp;</div>
				</div>
<div class="col-md-8 col-md-offset-2" >
			?????1<form id="form" role="form" action="<?= BASE_URL;?>roles/actionAgregar/" method="POST">
						<legend>Agregar Roles</legend>
<div class="row" >
																		<div class="form-group control-group col-md-2">
											<label for="id" class="control-label">id</label>
													<div class="controls">
														<input type="number" class="form-control" name="Roles[id]" id="id" placeholder="Grado" autofocus>
											</div>
								</div>
</form>
</div>
