<div class="row">
	<div class="col-md-12">&nbsp;</div>
</div>
<div class="row" >
	<div class="col-md-8 col-md-offset-2" >
		<form id="form" role="form" action="<?= BASE_URL;?>roles/actionEditar/" method="POST">
			<legend>Editar Roles</legend>
			<div class="form-group control-group col-md-2">
				<label for="nom_rol" class="control-label">nom_rol</label>
				<div class="controls">
					<input type="text" class="form-control" name="Roles[nom_rol]" id="nom_rol" placeholder="nom_rol">
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 col-md-offset-0" >
					<button type="submit" class="btn btn-primary" role="button">Editar</button>
					<a href="			<?= BASE_URL;?>roles/actionEditar/" class="btn btn-primary col-md-offset-1"  role="button">Volver</a>
				</div>
			</div>
		</form>
	</div>
</div>
	