<div class="row">
	<div class="col-md-12">&nbsp;</div>
</div>
<div class="row" >
	<div class="col-md-8 col-md-offset-2" >
		<form id="form" role="form" action="<?= BASE_URL;?>roles_usuarios/actionAgregar/" method="POST">
			<legend>Agregar RolesUsuarios</legend>
			<div class="form-group control-group col-md-2">
				<label for="usuario_id" class="control-label">usuario_id</label>
				<div class="controls">
					<input type="number" class="form-control" name="roles_usuarios[usuario_id]" id="usuario_id" placeholder="usuario_id">
				</div>
			</div>
			<div class="form-group control-group col-md-2">
				<label for="role_id" class="control-label">role_id</label>
				<div class="controls">
					<input type="number" class="form-control" name="roles_usuarios[role_id]" id="role_id" placeholder="role_id">
				</div>
			</div>
			<div class="form-group control-group col-md-2">
				<label for="fec_usu_rol" class="control-label">fec_usu_rol</label>
				<div class="controls">
					<input type="date" class="form-control" name="roles_usuarios[fec_usu_rol]" id="fec_usu_rol" placeholder="fec_usu_rol">
				</div>
			</div>
			<div class="row">
				<div class="col-md-12" >
					<button type="submit" class="btn btn-primary" role="button">Agregar</button>
					<a href="			<?= BASE_URL;?>roles_usuarios/actionAgregar/" class="btn btn-primary col-md-offset-1"  role="button">Volver</a>
				</div>
			</div>
		</form>
	</div>
		</div>
	<?php
if(isset($this->msg))
{?>
	<script id="msgModal">
		ejecutarModal("<?= $this->msg;?>","Agregar Roles_usuarios",{label: "Ok"});
	</script>
<?php
}
?>