<div class="row">
	<div class="col-md-12">&nbsp;</div>
</div>
<div class="col-md-8 col-md-offset-2" >
	<form id="form" role="form" action="<?= BASE_URL;?>roles_usuarios/actionAgregar/" method="POST">
		<legend>Agregar Roles_usuarios</legend>
		<div class="row" >
		2<div class="form-group control-group col-md-2">
			<label for="usuario_id" class="control-label">usuario_id</label>
			<div class="controls">
				<input type="number" class="form-control" name="Roles_usuarios[usuario_id]" id="usuario_id" placeholder="usuario_id">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="role_id" class="control-label">role_id</label>
			<div class="controls">
				<input type="number" class="form-control" name="Roles_usuarios[role_id]" id="role_id" placeholder="role_id">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="fec_usu_rol" class="control-label">fec_usu_rol</label>
			<div class="controls">
				<input type="date" class="form-control" name="Roles_usuarios[fec_usu_rol]" id="fec_usu_rol" placeholder="fec_usu_rol">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="id" class="control-label">id</label>
			<div class="controls">
				<input type="number" class="form-control" name="Roles_usuarios[id]" id="id" placeholder="id">
			</div>
		</div>
</div>
</form>
</div>
