<style>
        #map {
            height: 350px;
            background-color: #eee;
        }
        .olControlAttribution {
            bottom: 3px;
            left: 10px;
            line-height: 9px;
            font-size: 9px;
            color: #ccc;
        }
        
        img.olTileImage {
        max-width: none;
    }
    </style>

<!-- Tab panes -->
<div class="row">        
    <div class="col-md-8 col-md-offset-4">
        <div class="btn-toolbar" role="toolbar">
            <div class="btn-group">
            <button role="button" class="btn btn-primary" value="none" onclick="alternarControl(this);">
                <span class="glyphicon glyphicon-globe"></span>
            </button>
            <button role="button" class="btn btn-primary" value="drag" onclick="alternarControl(this);">
                <span class="glyphicon glyphicon-move"></span>
            </button>
            <button class="btn btn-primary" value="point" onclick="alternarControl(this);">
                <span class="glyphicon glyphicon-pushpin"></span>
            </button>
            <button role="button" class="btn btn-primary" value="line" onclick="alternarControl(this);">
                <span class="glyphicon glyphicon-pencil"></span>
            </button>
            <button role="button" class="btn btn-primary" value="" onclick="alternarControl(this);">
                <span class="glyphicon glyphicon-record"></span>
            </button>
            <button role="button" class="btn btn-primary" value="" onclick="alternarControl(this);">
                <span class="glyphicon glyphicon-screenshot"></span>
            </button>
            <button role="button" class="btn btn-primary" value="zoon" onclick="alternarControl(this);"> 
                <span class="glyphicon glyphicon-search"></span>
            </button>
            <button role="button" class="btn btn-primary" value="" onclick="alternarControl(this);"> 
                <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button role="button" class="btn btn-primary" value="" onclick="alternarControl(this);">
                <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
            <button role="button" class="btn btn-primary" value="box" onclick="alternarControl(this);">
                <span class="glyphicon glyphicon-stop"></span>
            </button>
            <button role="button" class="btn btn-primary" value="select" onclick="alternarControl(this);">
                <span class="glyphicon glyphicon-hand-up"></span>
            </button>
            <!--  <button role="button" class="btn btn-primary" value="">
                <span class="glyphicon glyphicon-zoom-out"></span>
              </button>-->
            </div>
          </div>
    </div>    
</div>
<div class="row">    
    <div class="col-md-4"> 
        
        <button role="button" class="btn btn-primary" value="box" onclick="alternarControl(this);">
            <span class="glyphicon glyphicon-arrow-down"></span>
        </button>
        <button role="button" class="btn btn-primary" value="box" onclick="alternarControl(this);">
            <span class="glyphicon glyphicon-arrow-left"></span>
        </button>
        <button role="button" class="btn btn-primary" value="box" onclick="alternarControl(this);">
            <span class="glyphicon glyphicon-arrow-right"></span>
        </button>
        <button role="button" class="btn btn-primary" value="box" onclick="alternarControl(this);">
            <span class="glyphicon glyphicon-arrow-up"></span>
        </button>        
        
        <div id="controls">
            <ul id="controlToggle">
                <li>
                    <input type="radio" name="type" value="none" id="noneToggle"
                           onclick="alternarControl(this);" checked="checked" />
                    <label for="noneToggle">navigate</label>
                </li>
                <li>
                    <input type="radio" name="type" value="point" id="pointToggle" onclick="alternarControl(this);" />
                    <label for="pointToggle">draw point</label>
                </li>
                <li>
                    <input type="radio" name="type" value="line" id="lineToggle" onclick="alternarControl(this);" />
                    <label for="lineToggle">draw line</label>
                </li>
                <li>
                    <input type="radio" name="type" value="polygon" id="polygonToggle" onclick="alternarControl(this);" />
                    <label for="polygonToggle">draw polygon</label>
                </li>
                <li>
                    <input type="radio" name="type" value="box" id="dragToggle"
                            onclick="alternarControl(this);" />
                    <label for="dragToggle">draw box</label>
                </li>
                <li>
                    <input type="radio" name="type" value="triangle" id="dragToggle"
                           onclick="alternarControl(this);" />
                    <label for="dragToggle">draw triangle</label>
                </li>
                <li>
                        <input type="radio" name="type" value="drag" id="dragToggle"
                           onclick="alternarControl(this);" />
                    <label for="dragToggle">drag feature</label>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-4">    
        <div id="map" style="border: 1px solid black;width: 100%;height: 65%;"></div>
    </div>
    <div class="col-md-4"> </div>
</div>
</body>
</html>
