<div class="row">
			<div class="col-md-12">&nbsp;</div>
		</div>
<div class="col-md-8 col-md-offset-2" >
	?????0<form id="form" role="form" action="<?= BASE_URL;?>usuarios/actionAgregar/" method="POST">
				<legend>Agregar Usuarios</legend>
<div class="row" >
														<div class="form-group control-group col-md-2">
									<label for="id" class="control-label">id</label>
											<div class="controls">
												<input type="number" class="form-control" name="Usuarios[id]" id="id" placeholder="Grado" autofocus>
									</div>
						</div>
</div>
						<div class="form-group control-group col-md-2">
							<label for="tel_usu" class="control-label">tel_usu</label>
									<div class="controls">
										<input type="number" class="form-control" name="Usuarios[tel_usu]" id="tel_usu" placeholder="Grado" autofocus>
							</div>
				</div>
</form>
</div>
