<div class="row">
	<div class="col-md-12">&nbsp;</div>
</div>
<div class="col-md-8 col-md-offset-2" >
	<form id="form" role="form" action="<?= BASE_URL;?>permisos_roles/actionAgregar/" method="POST">
		<legend>Agregar Permisos_roles</legend>
		<div class="row" >
		2<div class="form-group control-group col-md-2">
			<label for="id" class="control-label">id</label>
			<div class="controls">
				<input type="number" class="form-control" name="Permisos_roles[id]" id="id" placeholder="id">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="id_rol" class="control-label">id_rol</label>
			<div class="controls">
				<input type="number" class="form-control" name="Permisos_roles[id_rol]" id="id_rol" placeholder="id_rol">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="id_per" class="control-label">id_per</label>
			<div class="controls">
				<input type="number" class="form-control" name="Permisos_roles[id_per]" id="id_per" placeholder="id_per">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="fec_per_rol" class="control-label">fec_per_rol</label>
			<div class="controls">
				<input type="date" class="form-control" name="Permisos_roles[fec_per_rol]" id="fec_per_rol" placeholder="fec_per_rol">
			</div>
		</div>
</div>
<div class="row" >
</form>
</div>
