<div class="row">
	<div class="col-md-12">&nbsp;</div>
</div>
<div class="col-md-8 col-md-offset-2" >
	<form id="form" role="form" action="<?= BASE_URL;?>validadores_campos/actionAgregar/" method="POST">
		<legend>Agregar Validadores_campos</legend>
		<div class="row" >
		2<div class="form-group control-group col-md-2">
			<label for="id_campo" class="control-label">id_campo</label>
			<div class="controls">
				<input type="number" class="form-control" name="Validadores_campos[id_campo]" id="id_campo" placeholder="id_campo">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="id_val" class="control-label">id_val</label>
			<div class="controls">
				<input type="number" class="form-control" name="Validadores_campos[id_val]" id="id_val" placeholder="id_val">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="val_att_val_cam" class="control-label">val_att_val_cam</label>
			<div class="controls">
				<input type="text" class="form-control" name="Validadores_campos[val_att_val_cam]" id="val_att_val_cam" placeholder="val_att_val_cam">
			</div>
		</div>
		2<div class="form-group control-group col-md-2">
			<label for="val_msg_val_cam" class="control-label">val_msg_val_cam</label>
			<div class="controls">
				<input type="text" class="form-control" name="Validadores_campos[val_msg_val_cam]" id="val_msg_val_cam" placeholder="val_msg_val_cam">
			</div>
		</div>
</div>
<div class="row" >
0<div class="form-group control-group col-md-2">
	<label for="id" class="control-label">id</label>
	<div class="controls">
		<input type="number" class="form-control" name="Validadores_campos[id]" id="id" placeholder="id">
	</div>
</div>
</form>
</div>
