<div class="row">
			<div class="col-md-12">&nbsp;</div>
		</div>
<div class="col-md-8 col-md-offset-2" >
	?????0<form id="form" role="form" action="<?= BASE_URL;?>validadores_campos/actionAgregar/" method="POST">
				<legend>Agregar Validadores_campos</legend>
<div class="row" >
														<div class="form-group control-group col-md-2">
									<label for="id_campo" class="control-label">id_campo</label>
											<div class="controls">
												<input type="number" class="form-control" name="Validadores_campos[id_campo]" id="id_campo" placeholder="Grado" autofocus>
									</div>
						</div>
						<div class="form-group control-group col-md-2">
							<label for="id_val" class="control-label">id_val</label>
									<div class="controls">
										<input type="number" class="form-control" name="Validadores_campos[id_val]" id="id_val" placeholder="Grado" autofocus>
							</div>
				</div>
				<div class="form-group control-group col-md-2">
					<label for="id" class="control-label">id</label>
							<div class="controls">
								<input type="number" class="form-control" name="Validadores_campos[id]" id="id" placeholder="Grado" autofocus>
					</div>
		</div>
</div>
</form>
</div>
