<div class="row">
	<div class="col-md-12">&nbsp;</div>
</div>
<div class="row" >
	<div class="col-md-8 col-md-offset-2" >
		<form id="form" role="form" action="<?= BASE_URL;?>/action/" method="POST">
			<legend>Consultar Validadores_campos</legend>
			<div class="form-group control-group col-md-2">
				<label for="id_campo" class="control-label">id_campo</label>
				<div class="controls">
					<input type="number" class="form-control" name="Validadores_campos[id_campo]" id="id_campo" placeholder="id_campo">
				</div>
			</div>
			<div class="form-group control-group col-md-2">
				<label for="id_val" class="control-label">id_val</label>
				<div class="controls">
					<input type="number" class="form-control" name="Validadores_campos[id_val]" id="id_val" placeholder="id_val">
				</div>
			</div>
			<div class="form-group control-group col-md-2">
				<label for="val_att_val_cam" class="control-label">val_att_val_cam</label>
				<div class="controls">
					<input type="text" class="form-control" name="Validadores_campos[val_att_val_cam]" id="val_att_val_cam" placeholder="val_att_val_cam">
				</div>
			</div>
			<div class="form-group control-group col-md-2">
				<label for="val_msg_val_cam" class="control-label">val_msg_val_cam</label>
				<div class="controls">
					<input type="text" class="form-control" name="Validadores_campos[val_msg_val_cam]" id="val_msg_val_cam" placeholder="val_msg_val_cam">
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 col-md-offset-0" >
					<a href="			<?= BASE_URL;?>validadores_campos/actionConsultar/" class="btn btn-primary col-md-offset-1"  role="button">Volver</a>
				</div>
			</div>
		</form>
	</div>
</div>
	