<div class="row">
    <div class="col-md-12">&nbsp;</div>
</div>
<div class="col-md-8 col-md-offset-2" >    
    <form role="form" action="<?= BASE_URL;?>roles/actionGestionarInicio/<?=$this->id_rol?>" method="POST" onsubmit="seleccionarTodo();">
        <legend>Configurar Inicio de Rol</legend> 
        <div class="row">
            <div class="form-group control-group col-md-5">
                <label for="nom_rol" class="control-label">Items</label>
                <div class="controls">
                    <select multiple class="form-control" id="items" >
                        <?php
                        foreach ($this->indicadores as $value) 
                        {
                            echo '<option value="'.$value->id_ind.'">'.  ucwords(strtolower($value->nom_ind)).'</option>';
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group control-group col-md-2">
                <label for="nom_rol" class="control-label">&nbsp;</label>
                <div class="controls">
                    <button type="button" class="btn btn-primary" role="button" onclick="moverDesdeHasta('pan_ini','items');actualizarPagIni();actualizarItems();">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </button>               
                    <button type="button" class="btn btn-primary" role="button" onclick="moverDesdeHasta('items','pan_ini');actualizarPagIni();actualizarItems();">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </button>               
                </div>
            </div>
            <div class="form-group control-group col-md-4">
                <label for="nom_rol" class="control-label">Pantalla de Inicio</label>
                <div class="controls">
                    <select multiple="multiple" tabindex="1" class="form-control" name="indicadores[id_ind_ind_rol][]" id="pan_ini" >
                        <?php
                        foreach ($this->indicadores_rol as $value) 
                        {
                            echo '<option value="'.$value->id_ind.'">'.  ucwords(strtolower($value->nom_ind)).' ('.$value->pos_ind_rol.')</option>';
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group control-group col-md-1">
                <label for="nom_rol" class="control-label">&nbsp;</label>
                <div class="controls">
                    <button type="button" class="btn btn-primary" role="button" onclick="subir();">
                        <span class="glyphicon glyphicon-chevron-up"></span>
                    </button>               
                    <button type="button" class="btn btn-primary" role="button" onclick="bajar();">
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </button>               
                </div>
            </div>
        </div>
        <div class="form-group col-md-4 col-md-offset-5">
            <button type="submit" class="btn btn-primary" role="button">Actualizar</button>               
            <a href="<?= BASE_URL;?>roles" class="btn btn-primary col-md-offset-1" role="button">Volver</a>
        </div>
        <?php 
        if(isset($this->msg))
        {?>
            <script id="msgModal">
                ejecutarModal("<?= $this->msg;?>","Configurar Inicio de Rol",{label: "Ok"});
            </script>
        <?php
        }
        ?>
    </form>
</div>