<div class="row">
													<div class="col-md-12">&nbsp;</div>
												</div>
<div class="col-md-8 col-md-offset-2" >
											?????5<form id="form" role="form" action="<?= BASE_URL;?>validaciones/actionAgregar/" method="POST">
														<legend>Agregar Validaciones</legend>
<div class="row" >
																																		<div class="form-group control-group col-md-2">
																			<label for="id_val" class="control-label">id_val</label>
																					<div class="controls">
																						<input type="number" class="form-control" name="Validaciones[id_val]" id="id_val" placeholder="Grado" autofocus>
																			</div>
																</div>
</form>
</div>
