<div class="row">
    <div class="col-md-12">&nbsp;</div>
</div>
<div class="col-md-4 col-md-offset-5" >    
    <form id="form" role="form" action="<?= BASE_URL;?>contrasena/" method="POST">
        <legend>Cambiar Contraseña</legend>     
        <div class="row">
            <div class="form-group control-group col-md-6">
                <label for="pas_act" class="control-label">Contraseña Actual</label>
                <div class="controls">
                    <input type="password" class="form-control" name="contrasena[pas_act]" id="pas_act" placeholder="Contraseña Actual" autofocus>
                </div>
            </div>
        </div>
        <div class="row">            
            <div class="form-group control-group col-md-6">
                <label for="pas_nue" class="control-label">Contraseña Nueva</label>
                <div class="controls">
                    <input type="password" class="form-control" name="contrasena[pas_nue]" id="pas_nue" placeholder="Contraseña Nueva" >
                </div>
            </div>        
        </div>
        <div class="row">            
            <div class="form-group control-group col-md-6">
                <label for="pas_con" class="control-label">Confirmar Contraseña</label>
                <div class="controls">
                    <input type="password" class="form-control" name="contrasena[pas_con]" id="pas_con" placeholder="Confirmar Contraseña" >
                </div>
            </div>        
        </div>
        <div class="row">
            <div class="form-group col-md-12 col-md-offset-2 form-actions">
                    <button type="submit" class="btn btn-primary" role="button">Guardar</button>                       
            </div>
        </div>
        <?php 
        if(isset($this->msg))
        {?>
        <script id="msgModal">
            ejecutarModal("<?= $this->msg;?>","Cambiar Contraseña",{label: "Ok"});
        </script>
        <?php
        }
        ?>
    </form>
</div>