<div class="col-md-12" style="margin-top: 5px;"></div> 
<div class="col-md-4" style="margin-top: 5px;"></div> 
<div class="col-md-4" style="margin-top: 5px;"> 
    <form method="post" action="<?= BASE_URL."contrasena/restablecer/";?>">
        <div class="panel panel-default">
            <div class="panel-heading panel-title">Recuperar contaseña</div>
            <div class="panel-body">
                <div class="row">
                    <div class="form-group control-group col-md-9 col-md-offset-2">
                        <label for="log_usu" class="control-label">Usuario:</label>
                        <div class="controls">
                            <input type="text" class="form-control" name="usuario[log_usu]" id="log_usu" placeholder="Usuario"  required autofocus autocomplete="off"/>
                        </div>
                    </div>                    
                </div>
                <br>                
                <div class="row">
                    <div class="form-group control-group col-md-4 col-md-offset-3">
                        <input class="btn btn-lg btn-success" type="submit" value="Enviar" role="button"/>
                    </div>  
                    <div class="form-group control-group col-md-4 col-md-offset-0">                        
                        <a href="<?= BASE_URL;?>" class="btn btn-lg btn-success" role="button">Volver</a>        
                    </div>  
                </div>                
                <?php         
            if(isset($this->msg))
            {?>
                <div class="row" style="margin-top: 15px;" >
                    <div class="col-md-1"></div>
                    <div class="col-md-10 alert <?= $this->class;?> text-center">
                        <div style="margin-left: 35px">
                            <h4><?= $this->msg;?>
                            </h4>
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                </div>
            <?php
            }
            ?>                
            </div>
        </div>
    </form>
</div>   
