<div class="row">
																	<div class="col-md-12">&nbsp;</div>
																</div>
<div class="col-md-8 col-md-offset-2" >
															?????7<form id="form" role="form" action="<?= BASE_URL;?>origen_campos/actionAgregar/" method="POST">
																		<legend>Agregar Origen_campos</legend>
<div class="row" >
																																										<div class="form-group control-group col-md-2">
																							<label for="id" class="control-label">id</label>
																									<div class="controls">
																										<input type="number" class="form-control" name="Origen_campos[id]" id="id" placeholder="Grado" autofocus>
																							</div>
																				</div>
</form>
</div>
