<div class="col-md-12" style="margin-top: 5px;"></div> 
<div class="col-md-4" style="margin-top: 5px;"></div> 
<div class="col-md-4" style="margin-top: 5px;"> 
    <div class="row" style="margin-top: 15px;" >
        <div class="col-md-1"></div>
        <div class="col-md-10 alert alert-danger">
            <div style="margin-left: 35px">
                <h4>
                    No posee los permisos necesarios para visualizar esta funcionalidad
                </h4>                
                <a href="<?= BASE_URL;?>" class="btn btn-primary col-md-offset-4" role="button" onclick="window.location.href=document.referrer;">Volver</a>        
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>